name: Update Feature Store

on:
  schedule:
    - cron: '15 20 * * 4'

jobs:
  update_feature_store:
    runs-on: ubuntu-latest

    env:
      HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      HOPSWORKS_PROJECT_NAME: ${{ secrets.HOPSWORKS_PROJECT_NAME }}
      FEATURE_GROUP_NAME: ${{ secrets.FEATURE_GROUP_NAME }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
        cache: pip

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Fetch and Prepare Data
      run: |
        python src/fetch_data.py
